   o p e n a p i :   3 . 0t.y1p
   ei:n fsot:r
   i n gt
   i t l e :   V a n n a   C u s t o m  dGePsTc rAiPpIt
   i o nv:e rUssieorn :e m1a.i0l. 0f
   osre rtvrearcsk:i
   n g 
   -   u r l :   h t t p s : / / y oaugre-natp_pi.dr:a
   i l w a y . a p p 
    p a t h s : 
        t/yqpuee:r ys_tvrainnnga
        : 
                 p o s t : 
                              odpeesrcartiipotniIodn::  qVuaenrnyaV aangnean
                              t   I D   ( mraenqdureaskteB)o
                              d y : 
                                               r e q u i r edde:f aturlute:
                                                 m a n d r a k ec
                                                 o n t e n t :r
                                                 e s p o n s e s : 
                                                   a p p l i c a t'i2o0n0/'j:s
                                                   o n : 
                                                                 d e s c r ispcthieomna:: 
                                                                 S u c c e s s f u l   q u e rtyy pree:s poobnjseec
                                                                 t 
                                                                                   c o n t e nptr:o
                                                                                   p e r t i e s : 
                                                                                           a p p l i c a t i o n / jmseosns:a
                                                                                           g e : 
                                                                                                                 s c h e m a : 
                                                                                                                 t y p e :   s t r i n g 
                                                                                                                         t y p e :   o b j e c t 
                                                                                                                         u s e r _ e m a i l : 
                                                                                                                                   p r o p e r t i e s : 
                                                                                                                                       t y p e :   s t r i n g 
                                                                                                                                               s u c c e s s : 
                                                                                                                                                       a g e n t _ i d : 
                                                                                                                                                                     t y p e :   b o o l e atny
                                                                                                                                                                     p e :   s t r i n g 
                                                                                                                                                                                     d a t a : 
                                                                                                                                                                                               d e f a u l t :   m a n d r a ktey
                                                                                                                                                                                               p e :   o b jreecstp
                                                                                                                                                                                               o n s e s : 
                                                                                                                                                                                                                ' 2 0 0m'e:s
                                                                                                                                                                                                                s a g e : 
                                                                                                                                                                                                                          d e s c r i p t i o n :   S u ctcyepses: string
                                                                                                                                                                                                                                  '400':
                                                                                                                                                                                                                                            description: Bad request
                                                                                                                                                                                                                                                    '500':
                                                                                                                                                                                                                                                              description: Internal server error
